import "./globals.css";
import Nav from "./(components)/Nav/page";
import AuthProvider from "./(components)/AuthProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body>
          <div className="bg-slate-200 w-full">
            <Nav />
          </div>
          <div>{children}</div>
        </body>
      </AuthProvider>
    </html>
  );
}
